"""add reactions table

Revision ID: 99633aab5b92
Revises: dfef3a26e564
Create Date: 2026-02-11 23:02:15.673680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99633aab5b92'
down_revision: Union[str, None] = 'dfef3a26e564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('emoji', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'emoji', 'agent_id', name='uq_reaction_entity_emoji_agent'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'emoji', 'user_id', name='uq_reaction_entity_emoji_user')
    )
    op.create_index('ix_reactions_entity', 'reactions', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reactions_entity', table_name='reactions')
    op.drop_table('reactions')
    # ### end Alembic commands ###
